### ISSUE TITLE
Exception when try create a Postgres connection

### ISSUE THREAD

**Issue by yuricastro51** [FastReports/FastReport#681]
**Describe the bug**
When I try to create a Postgres connection, is happing an exception.

**To Reproduce**
1. Go to 'Data'
2. Click on 'Add Data Source...'
3. Click on 'New connection...'
4. Select the **Postgres connection**  option
5. Click on 'Test connection'
7. See error

**Expected behavior**
To connect on database

**Stacktrace**
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/10470559/2fa1fd28-d575-4cc6-8636-74d778ce2364)

**Device (please complete the following information):**
 - OS: Wiin 11

**Comment by rftd** [comment]
I have the same problem

**Comment by BogdanStegachev** [comment]
Hello!

Reproduced your issue, created a task and passed it to the development department, expect a fix in the next version of FastReport Community Edition

Best regards,
Bogdan

**Comment by RieMomo** [comment]
I have the same problem too.

**Comment by rftd** [comment]
@RieMomo Im using this as paliative

https://github.com/rftd/FastReport.Design.Avalonia

Its a custom designer with plugin manager, using the demo version of FastReport.Avalonia.

**Comment by MaratAlaev** [comment]
Hello!

The problem has been solved in the new version

**Comment by BogdanStegachev** [comment]
Hello!

Reproduced this issue, passed your feedback to the development department, expect changes in the next versions of FastReport Community Edition

Best regards,
Bogdan

**Comment by AkaiTheAlone** [comment]
im still having this isse over here. haven't they solved it yet?
![image](https://github.com/user-attachments/assets/39b2158c-04d6-46d7-82bd-1f55936a5e31)

**Comment by BogdanStegachev** [comment]
Hello!

At the moment the problem under the query from this task is not solved and is under development, changes will be in the next minor or major releases of FastReport Community Edition

Best regards,
Bogdan

**Comment by EvgenyJSmith** [comment]
add to config Designer.exe.config:

<dependentAssembly>
    <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
    <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.3.0"/>
</dependentAssembly>
